apiVersion: apps/v1
kind: Deployment
metadata: 
  name: studentapp
  labels:
    app: studentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
        - name: studentapp
          image: <>
          ports: 
            - containerPort: 8080
            