apiVersion: v1
kind: Service
metadata:
  name: studentapp-service
  labels:
    app: studentapp
spec:
  selector:
    app: studentapp
  type: LoadBalancer
  ports:
    - name: java
      port: 8080
      targetPort: 8080
      protocol: TCP
